FROM @@USER@@/docker-ubuntu-builder:20.04

# rockchip tools
RUN apt-get update && apt-get install --no-install-recommends -y \
	libusb-1.0-0-dev \
	&& apt-get clean

# debootstrap
RUN apt-get update && apt-get install --no-install-recommends -y \
	binfmt-support qemu-user-static \
	debootstrap debian-archive-keyring \
	&& apt-get clean

# misc tools required for building
RUN apt-get update && apt-get install --no-install-recommends -y \
	bc \
	device-tree-compiler \
	python3-dev \
	swig \
	u-boot-tools \
	&& apt-get clean

# cross compile linux and uboot
RUN apt-get update && apt-get install --no-install-recommends -y \
	gcc-aarch64-linux-gnu \
	gcc-multilib-arm-linux-gnueabi \
	gcc-multilib-arm-linux-gnueabihf \
	bison \
	flex \
	libncurses-dev \
	libssl-dev \
	&& apt-get clean
