FROM @@USER@@/docker-ubuntu-builder:18.04

# dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
	libusb-1.0-0-dev \
	&& apt-get clean

# debootstrap
RUN apt-get update && apt-get install --no-install-recommends -y \
	binfmt-support qemu-user-static \
	debootstrap debian-archive-keyring \
	&& apt-get clean
